version: "3.9"
services:
  jenkins:
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    build: .
    hostname: jenkins-container
    container_name: jenkins-custom
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8089:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
