jenkins:
  slaveAgentPort: 50000
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: true
  labelAtoms:
    - name: "no-use-this-node"
    - name: "built-in"
  labelString: "no-use-this-node"
  mode: NORMAL
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
          name: "Jenkins Admin"
          properties:
            - timezone:
                timeZoneName: "Asia/Saigon"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - entries:
              - user: ${JENKINS_ADMIN_ID}
            name: "Administrators"
            pattern: ".*"
            permissions:
              - "Overall/Administer"
  projectNamingStrategy:
    roleBased:
      forceExistingJobs: true
security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
unclassified:
  location:
    url: ${JENKINS_URL}
  thinBackup:
    backupAdditionalFiles: false
    backupBuildArchive: false
    backupBuildResults: true
    backupBuildsToKeepOnly: false
    backupConfigHistory: false
    backupNextBuildNumber: false
    backupPath: "/jenkins_backup"
    backupPluginArchives: false
    backupUserContents: false
    cleanupDiff: false
    diffBackupSchedule: "H 18 * * 1-5"
    failFast: true
    forceQuietModeTimeout: 120
    fullBackupSchedule: "H 23 * * 1-5"
    moveOldBackupsToZipFile: true
    nrMaxStoredFull: 12
    waitForIdle: true
  globalTimeOutConfiguration:
    operations:
      - "abortOperation"
    overwriteable: false
  scheduleBuild:
    defaultScheduleTime: "10:00:00 PM"
    timeZone: "Asia/Saigon"
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - simpleBuildDiscarder:
          discarder:
            logRotator:
              numToKeepStr: "15"
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '."
    systemTimeFormat: "yyyy-MMM-dd hh:mm:ss a zzz' | '."
